### ISSUE TITLE
Add XML tag for tcpflow scanners

### ISSUE THREAD

**Issue by olibre** [dfxml-working-group/dfxml_schema#24]
On tcpflow pull request discussion (https://github.com/simsong/tcpflow/pull/160#issuecomment-306074872), an idea emerged: Adding XML tag for scanner purpose. The idea is that a scanner processes a flow file and adds annotations within the DFXML file (report.xml). 

For example, a new tcpflow scanner "python" delegates the processing to an external python script. This python script can return the result as a string. When python script returns a string this string is appended in the report.xml.

Please propose your thought in order to specify a new generic XML tag for any tcpflow scanner. 

Something like:

    <result scanner="python">bla bla bla</result>

or more generic:

    <scanner name="python" type="info">elapsed time, consumed memory...</result>
    <scanner name="python" type="result">bla bla bla</result>

or something else:

    <scanner name="python" process="post" info="path/module/function, timing..." type="result">bla bla bla</result>

or even more complex:

    <scanner name="python" run="1">
        <stage>post-process</stage>
        <parameters>path/module/function</parameters>
        <log>raised an IO exception at line 42</log>
        <result>bla bla bla</result>
    </scanner>

Please provide some feedback :-)

**Comment by slippery60** [comment]
I think it is a good idea.  It will help in locating / investigating
network intrusions.

**Comment by olibre** [comment]
The https://github.com/simsong/tcpflow/pull/160#issuecomment-306074872 is a continuation of the @jakesmo & @lassimus work in order to integrate a new scanner for tcpflow that calls an external python script. There is something very interesting about the @jakesmo & @lassimus work: the ability for a scanner to write some result within the DFXML file. 

Voilà the corresponding C++ source code:

```cpp
PyObject* pResult = PyObject_CallObject(pythonFunction, pArgs);
if (pResult) {
    // If XML-reporting enabled => Insert the returned string from the function
    if (sp.sxml) {
        const char* ptr = PyString_AsString(pResult);
        if (ptr)
            (*sp.sxml) << "<scan_python_result>"<< ptr <<"</scan_python_result>";
        else
            (*sp.sxml) << "<scan_python_result/>";
    }
}
```

However, we have to generalize the XML tag `<scan_python_result>` in order to be reused by the other scanners.

This is why I was proposing something like `<scanner name="scan_python" type="result">...bla.bla.bla...</scanner>`

The idea is to find a new generic XML tag with appropriate attributes but also to keep DFXML simple and obvious. This new XML tag may be used by any scanner to provide KPIs, log info, related data... 
 
What are your thoughts?

**Comment by ajnelson-nist** [comment]
Hi.  I see how attaching scanner output to the flow breakouts can be helpful.  However, I think there are a few issues with this request.  First, "Scanner" is a pretty generic term, so to integrate that into the core DFXML vocabulary, the schema definition would need to be conscious of other tools that would probably want to use the same element name in the future.  Off the top of my head, [Bulk Extractor](https://github.com/simsong/bulk_extractor) may have a conflict here, because its concept of "scanner" matches most semantics of what you're requesting, but may not have the same vocabulary requirements for sub elements.

Second, I'm a bit confused about some of the requested XML structures.  The sample XML you provided here and in the tcpflow tracker have different attributes, element names, and child content structure.  So it looks to me like the scanner results' XML recording is in the design phase.

I think it would be helpful to take a different approach first, rather than trying to jump straight into adding to the DFXML schema.  Why don't you start with devising some XML under a tcpflow namespace, and design an API around it?  It will be much easier to discuss the goals of this scanner output format with examples of what does and doesn't work.

To help out with this, I've drafted some code based on a guess of what your scanner data will look like (especially based on your more complex example).  See the [`tcpflow_objects`](https://github.com/simsong/dfxml/tree/tcpflow_objects) branch of the DFXML code base.  These commands will run [a test](https://github.com/simsong/dfxml/blob/tcpflow_objects/python/test_Objects/test_TCPFlowObjects.py) of a [made-up example](https://github.com/simsong/dfxml/blob/tcpflow_objects/samples/tcpflow_zip_generic_header.xml) of discovered zip headers:

    cd .../dfxml/python/test_Objects
    make check-tcpflow

It is most certainly not exactly what you'll want---e.g. I wasn't sure what purpose the `name` and `type` attributes served with respect to each other.  But hopefully that gives you a good starting point to design and consume scanner output with no modifications needed to the DFXML framework.

**Comment by olibre** [comment]
Thank you @ajnelson-nist for your proposition.  
First, I am not sure what I want /ö\ 
(my propositions were just some brain storming)
Therefore I will adapt to your ideas.

I will have more time in further weeks and I will give you feedback.
Once I adapt my pull request on tcpflow and @simsong accepts it,
we can merge your branch tcpflow_objects to master.

See you in some weeks,
olibre

**Comment by olibre** [comment]
Hi @ajnelson-nist 

I like your idea about `<tcpflow:*>` namespace 😉 

```xml
<dfxml
  xmlns='http://www.forensicswiki.org/wiki/Category:Digital_Forensics_XML'
  xmlns:dc='http://purl.org/dc/elements/1.1/'
  xmlns:tcpflow='http://www.forensicswiki.org/wiki/Category:Digital_Forensics_XML#tcpflow'
  version='1.1.1'>
```

What is the process to update/maintain http://www.forensicswiki.org/wiki/Category:Digital_Forensics_XML#tcpflow


I have some comments about `<tcpflow:scanner_result>`

This is from your example:

```xml
<fileobject>
  <tcpflow:scanner_result name="zip_generic_header_detector" type="Python">
    <byte_runs>
      <byte_run img_offset="1234" len="30" />
      <byte_run img_offset="2345" len="30" />
    </byte_runs>
  </tcpflow:scanner_result>
  <filename>205.134.188.162.00080-008.030.072.112.38568</filename>
  <filesize>4135</filesize>
</fileobject>
```

I propose some changes:

```xml
<fileobject>
  <tcpflow:result scan="python" name="zip_generic_header_detector">
    <byte_runs>
      <byte_run img_offset="1234" len="30" />
      <byte_run img_offset="2345" len="30" />
    </byte_runs>
  </tcpflow:result>
  <filename>205.134.188.162.00080-008.030.072.112.38568</filename>
  <filesize>4135</filesize>
</fileobject>
```

I think `<tcpflow:result>` is more generic (more reusable, tinier, nicer).  
Using `scan="python"` show this result is from the `scan-python`.

But I also agree with this wording I you prefer:

```xml
<tcpflow:result scanner="python" name="zip_generic_header_detector">
```

I see your below comment. Do you want I modify tcpflow source code to use something like `<tcpflow:stat>`?  (this will be another pull request)

```xml
<!--This element isn't in the DFXML schema.  Should be namespaced and re-named.
<tcpflow startime='2013-05-15T10:21:07.936300Z' endtime='2013-05-15T10:21:07.957313Z' src_ipn='205.134.188.162' dst_ipn='8.30.72.112' mac_daddr='58:94:6b:7c:37:8c' mac_saddr='b4:14:89:61:fe:c0' packets='5' srcport='80' dstport='38568' family='2' />
-->
```

Do you know what @simsong think about this XML namespace?

**Comment by olibre** [comment]
Hi @ajnelson-nist 

I have implemented something similar what I have proposed on my last comment.
See pull request https://github.com/simsong/tcpflow/pull/164

The following XML code is an extract of one DFXML I have generated using `tcpflow`:

```xml
<fileobject>
  <filename>192.168.000.010.38797-174.141.234.172.00080c1</filename>
  <filesize>93</filesize>
  <tcpflow startime="2017-07-20T00:16:14.699700Z" endtime="2017-07-20T00:16:22.097782Z" src_ipn="192.168.0.10" dst_ipn="174.141.234.172" mac_daddr="00:24:d4:c3:cb:f2" mac_saddr="44:6d:57:79:eb:c4" packets="8" srcport="38797" dstport="80" family="2"/>
  <tcpflow:result scan="python" path="python/plugins" module="samplePlugin" function="sampleFunction">This message appears in the XML tag 'tcpflow:result' of report.xml (DFXML).</tcpflow:result>
</fileobject>
```

I have added XML tag **`tcpflow:result`** and its attributes:

- `scan`
- `path`
- `module`
- `function`

I hope you agree with that.  
What do you think?

Otherwise, the XML tag `tcpflow` is not part of DFXML schema as you mentioned.
We could propose to rename it to something like `tcpflow:info`...
But, within the tcpflow source code, there are other XML tags not conforming DFXML schema:

    $ grep 'sxml.*[ "]<[a-z]' -RI src/*
    src/scan_http.cpp:    if(sp.sxml) (*sp.sxml) << "\n    <byte_runs>\n";
    src/scan_python.cpp: (*sp.sxml) << "<tcpflow:result scan=\"python\" "
    src/scan_wifiviz.cpp:  (*sp.sxml) << "<ssids>\n";
    src/scan_wifiviz.cpp:    (*sp.sxml) << "  <ssid mac='" << (*it).first.mac <<"' ssid='" << dfxml_writer::xmlescape((*it).first.ssid) << "' count='" <<

List of XML tags not conforming DFXML schema:

- `tcpflow`
- `byte_runs`
- `ssids`

**Comment by ajnelson-nist** [comment]
Hi!

We can resolve the other non-conforming tags in a separate thread.

As for the `tcpflow:result` element, I still don't quite understand the purpose of the `@scan` attribute.  I'm curious to know what it's telling a later consumer of the XML.  Is it just representing the C++ file path?  What would you want to do to adjust `scan_wifiviz.cpp`'s XML output, since it seems like that will come up in the discussion on other not-namespaced, tcpflow-specific tags?

**Comment by olibre** [comment]
The `@scan` attribute is about the tcpflow option `-e`

The `tcpflow --help` says:

```
These scanners disabled by default; enable with -e:
   -e http - enable scanner http
   -e md5 - enable scanner md5
   -e netviz - enable scanner netviz
   -e python - enable scanner python
   -e wifiviz - enable scanner wifiviz

These scanners enabled by default; disable with -x:
   -x tcpdemux - disable scanner tcpdemux
```

There are six values for the attribute `@scan`.
Only the value `python` is used, and for some years...

But, who knows, one day someone may reuse tag `tcpflow:result`for another scanner...

Do I have answered your question?

**Comment by ajnelson-nist** [comment]
Ah, ok.  Yes, that answers that question.  I personally think `@scanner` would be a better attribute name to better match the help documentation, but that's a minor point.

These look fine to me.  I see your changes got merged into tcpflow.

As for your earlier question about maintaining the `tcpflow:` namespace: The maintenance is user driven.  It's helpful to language discussions to take a pragmatic approach, such as a use case, prototype code, and/or demonstration data.  At the moment, there isn't an XML schema for the `tcpflow:` namespace, so it can be pretty a friction-less process to put elements and attributes under that namespace, especially with only one XML-generating program that would be populating it.  In contrast, DFXML has several generating programs, so modifying that language takes a bit more notice and/or discussion.

I think this message thread has sufficiently addressed the thread title.  If there are other tcpflow-specific issues you'd like to discuss (like the non-DFXML-conforming elements), why don't we take it over to the tcpflow issue tracker?

**Comment by olibre** [comment]
Thank you very much @ajnelson-nist for your nice feedback.
I will rename `@scan` to `@scanner`...
Cheers 😋
